# -*- coding: utf-8 -*-
"""aula_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ASoVev652wBzHaSSx8NTpmzTmNpC5DH
"""

import pandas as pd

#A fonte dos dados está disponível neste link
fonte = 'https://github.com/alura-cursos/imersao-dados-2-2020/blob/master/MICRODADOS_ENEM_2019_SAMPLE_43278.csv?raw=true'

dados = pd.read_csv(fonte) #criando o Data Frame 'dados'
dados.head() #exibindo as primeiras linhas do data frame

dados.shape #explorando a forma do data frame (linhas, colunas)

dados.describe()

dados.columns.values #colunas presentes no data frame

dados['SG_UF_RESIDENCIA'].unique() #lista de estados presentes no dataframe

len(dados['SG_UF_RESIDENCIA'].unique()) #quantidade de estados

dados['SG_UF_RESIDENCIA'].value_counts() #quantidade de valores de cada estado

dados['NU_IDADE'].value_counts().sort_index() #distribuição por idades

#histograma da distribuição por idades
histograma1 = dados['NU_IDADE'].hist(bins=20, figsize=(10,8))
histograma1.set_title('Distribuição de idade dos participantes')

#qual a proporção de inscritos por idade?

total = len(dados['NU_IDADE'])
contagem = dados['NU_IDADE'].value_counts()
percentual = (100*contagem)/total
print(percentual)

#vimos que existem inscritos de 13 anos, de quais estados eles são?

dados.query('NU_IDADE == 13')['SG_UF_RESIDENCIA']

#analisando a quantidade de treineiros por idade

dados.query('IN_TREINEIRO == 1')['NU_IDADE'].value_counts().sort_index()

#analisando as notas das provas

provas = ['NU_NOTA_REDACAO', 'NU_NOTA_LC', 'NU_NOTA_MT','NU_NOTA_CN','NU_NOTA_CH']
dados[provas].describe()

dados['NU_NOTA_REDACAO'].hist(bins = 20) #histograma das notas da redação

dados['NU_NOTA_LC'].hist(bins = 20) #histograma de notas de Linguagens e Códigos

dados[provas].boxplot(figsize=(10,8))

#Na prova de linguagens e códigos o candidato pode escolher entre inglês e espanhol.
dados['TP_LINGUA'] #ingês:0, espanhol:1

#quantidade de candidatos que escolheram cada idioma
dados['TP_LINGUA'].value_counts()

#histograma com as notas de linguagem de acordo com a escolha do idioma

import matplotlib.pyplot as plt

ingles = dados.loc[dados['TP_LINGUA'] == 0]
espanhol = dados.loc[dados['TP_LINGUA'] == 1]

ingles['NU_NOTA_LC'].hist(bins = 20, alpha = 0.7)
espanhol['NU_NOTA_LC'].hist(bins = 20, alpha = 0.7)

plt.legend(['Inglês', 'Espanhol'])
plt.title('Notas por escolha de idioma')

ingles['NU_NOTA_LC'].max() #nota máxima do candidato que escolheu ingles

espanhol['NU_NOTA_LC'].max() #nota máxima do candidato que escolheu espanhol

ingles['NU_NOTA_LC'].mean() #nota média do candidato que escolheu ingles

espanhol['NU_NOTA_LC'].mean() #nota média do candidato que escolheu espanhol

